FROM debian:buster

RUN	apt-get update && apt-get -y install nginx
RUN apt-get update && apt-get -y install mariadb-server
RUN apt-get update && apt-get -y install php-fpm php-mysql
RUN apt-get update && apt-get -y install php-mbstring php-zip php-gd
